# Generated by Django 3.0.5 on 2020-06-08 07:52

import KiemTra.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KiemTra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baikiemtra',
            name='NoiDung',
            field=models.FileField(blank=True, default='Khong co bai kiem tra', upload_to=KiemTra.models.taoPathChoBaiKT),
        ),
        migrations.CreateModel(
            name='DeTuLuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenDe', models.CharField(max_length=100)),
                ('NoiDungDe', models.FileField(blank=True, default='Khong co de', upload_to=KiemTra.models.taoPathChoDeTuLuan)),
                ('HuongDanGiai', models.FileField(blank=True, default='Khong co huong dan giai', upload_to=KiemTra.models.taoPathChoDeTuLuan)),
                ('mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KiemTra.Mon')),
            ],
        ),
    ]
