# Generated by Django 3.0.5 on 2020-06-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KiemTra', '0002_auto_20200608_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='mon',
            name='MaMon',
            field=models.CharField(blank=True, default='thu', max_length=10),
        ),
        migrations.AlterField(
            model_name='thanhtich',
            name='Diem',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
