# Generated by Django 3.0.5 on 2020-06-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KiemTra', '0003_auto_20200616_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='baikiemtra',
            name='MaBai',
            field=models.CharField(blank=True, default='thu', max_length=10),
        ),
    ]
