# Generated by Django 3.0.5 on 2020-06-17 12:41

import KiemTra.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KiemTra', '0004_baikiemtra_mabai'),
    ]

    operations = [
        migrations.AddField(
            model_name='baikiemtra',
            name='HinhLienQuan',
            field=models.ImageField(blank=True, default='Khong co', upload_to=KiemTra.models.taoPathChoBaiKT),
        ),
    ]
