# Generated by Django 3.0.5 on 2020-06-17 12:52

import KiemTra.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KiemTra', '0005_baikiemtra_hinhlienquan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baikiemtra',
            name='HinhLienQuan',
        ),
        migrations.CreateModel(
            name='HinhLienQuanBaiKT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HinhLienQuan', models.ImageField(blank=True, default='Khong co', upload_to=KiemTra.models.taoPathChoBaiKT)),
                ('baikiemtra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KiemTra.BaiKiemTra')),
            ],
        ),
    ]
